name: t2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dask=2022.6.1
  - distributed=2022.6.1
  - intake==0.6.5
  - xarray=2022.10.0
  - xesmf=0.6.2
  - cartopy=0.20.3
  - geopandas=0.9.0
  - scipy=1.8.1
  - netcdf4=1.6.0
  - pip
  - pip:
    - bokeh==2.4.0
    - cf_units
    - hvplot
    - pytest-cov
    - pytest
    - shapely
    - metpy
    - plotly
    - pyarrow