name: geokube-0.2a4
channels:
  - conda-forge
dependencies:
  - cf-units
  - python=3.10.8
  - cartopy
  - numpy=1.23.5
  - pandas=1.4.3
  - netCDF4
  - scipy 
  - xarray=2022.6.0
  - dask=2023.1.1
  - esmpy=8.2.0
  - xesmf=0.6.3
  - intake=0.6.6
  - hvplot