name: geokube
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - cartopy
  - 'bokeh>=2.4.2,<3'
  - numpy=1.23.5
  - pandas=1.4.3
  - netCDF4
  - scipy 
  - xarray=2022.6.0
  - dask=2023.1.1
  - intake=0.6.6
  - esmpy=8.2.0
  - xesmf=0.6.3
