name: Build Docker image of the GEOKUBE component and push to the dev repository

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Docker image tag name
      run: echo "TAG=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV
    - uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install WHEEL tool
      run: pip install wheel
    - name: Build WHEEL file
      run: python setup.py bdist_wheel
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v2
      with:
        username: nologin
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_DEV_REPO_URL }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: | 
          ${{ secrets.DOCKER_DEV_REPO_URL }}/geokube:${{ env.TAG }}
          ${{ secrets.DOCKER_DEV_REPO_URL }}/geokube:latest      
