name: Build Docker image of the GEOKUBE component and push to the production repository

on:
  push:
    tags:        
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get release tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Log in to the docker repo
      run: docker login ${{ secrets.DOCKER_PROD_REPO_URL }} -u nologin -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_PROD_REPO_URL }}/geokube:${{ env.RELEASE_TAG }} -f Dockerfile .
    - name: Push docker image
      run: docker push ${{ secrets.DOCKER_PROD_REPO_URL }}/geokube:${{ env.RELEASE_TAG }}
