name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, edited, assigned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9    
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          python-version: 3.9

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Conda create environemnt
        shell: bash -l {0}
        run: conda create --name gk   

      - name: Conda activate
        shell: bash -l {0}
        run: conda activate gk       

      - run: |
          conda install cartopy

      - run: |
          conda install -c conda-forge xesmf 

      - name: Conda list
        shell: pwsh
        run: conda list       
          
      - run: conda run pip install pytest-github-actions-annotate-failures           
        
      - run: |
          conda run python setup.py install

      - name: Run pytest
        shell: bash -l {0}
        run: conda run pytest tests