name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, edited, assigned, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install WHEEL tool
        run: pip install wheel

      - name: Build WHEEL file
        run: python setup.py bdist_wheel

      - name: Install Geokube
        run: pip install dist/geokube-0.2.7-py3-none-any.whl

      - name: Run test
        run: pytest tests

