name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, edited, assigned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9    
        
      - name: Install dependencies  
      - run: |
          conda activate base
      - run: |
          conda install cartopy
      - run: |
          conda install -c conda-forge xesmf 
          
      - name: Install plugin for annotating failures
        run: pip install pytest-github-actions-annotate-failures           
        
      - run: |
          python setup.py install
          
      - name: Run PyTest
      - run: |
          pytest tests/