name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, edited, assigned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9    

      - name: Install Python dependencies
        run: |     
          pip install pytest
      - name: Install plugin for annotating failures
        run: pip install pytest-github-actions-annotate-failures          
      
      - run: |
          pytest test/
