name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, edited, assigned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Python dependencies
        run: |     
          pip install pytest

      - name: Test with PyTest
        run: |
          pytest tests/
