name: Unit Tests

on:
  workflow_run:
    workflows: [ 'build' ]
    types: [ completed ]
    branches:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.GEOKUBE_REGISTRY }}/geokube:latest
      credentials:
        username: nologin
        password: ${{ secrets.SCALEWAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Run test
        run: pytest tests

