name: Publish geokube package to TestPyPI

on: 
  release:
    types: [prereleased]  
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build geokube and publish to TestPyPI
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
#    environment:
#        name: testpypi
#        url: https://test.pypi.org/p/geokube
    permissions:
        id-token: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tool
        run: python3 -m pip install build --user
      - name: Build wheels
        run: python -m build --sdist --wheel --outdir=dist/ .
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: testpypi
        url: https://test.pypi.org/p/geokube
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      # retrieve your distributions here